### ISSUE TITLE
calendar is broken

### ISSUE THREAD

**Issue by all-yall** [animenotifier/notify.moe#243]
when going to the calendar, [https://notify.moe/calendar](https://notify.moe/calendar)
instead of the calendar is a long stream of error messages. It seems like they are cut off towards the bottom.
Edit: I also did try incognito to get rid of cookies and chrome and firefox just in case it was something on my end, but the error persisted regardless.
```
runtime error: invalid memory address or nil pointer dereference

goroutine 139805 [running]:
github.com/animenotifier/notify.moe/middleware.Recover.func1.1(0xf73f20, 0xc01b669b80)
/home/eduard/notify.moe/middleware/Recover.go:30 +0xdb
panic(0xcd3260, 0x156c870)
/usr/lib/go/src/runtime/panic.go:679 +0x1b2
github.com/animenotifier/notify.moe/pages/calendar.Get(0xf74020, 0xc022c1e6a0, 0xc000075a50, 0x42aaea)
/home/eduard/notify.moe/pages/calendar/calendar.go:53 +0x3d8
github.com/animenotifier/notify.moe/middleware.Layout.func1(0xf74020, 0xc022c1e6a0, 0xc000075a78, 0x203008)
/home/eduard/notify.moe/middleware/Layout.go:47 +0x90
github.com/animenotifier/notify.moe/middleware.UserInfo.func1(0xf74020, 0xc022c1e6a0, 0xa47c7098e0a2b, 0xc036259366)
/home/eduard/notify.moe/middleware/UserInfo.go:19 +0x3d
github.com/animenotifier/notify.moe/middleware.Session.func1(0xf74020, 0xc022c1e6a0, 0x15835c0, 0xc000075b68)
/home/eduard/notify.moe/middleware/Session.go:9 +0x3d
github.com/animenotifier/notify.moe/middleware.Log.func1(0xf74020, 0xc022c1e6a0, 0x11, 0x0)
/home/eduard/notify.moe/middleware/Log.go:38 +0x6d
github.com/animenotifier/notify.moe/middleware.OpenGraph.func1(0xf73f20, 0xc01b669b80, 0x5, 0xc0234e6e60)
/home/eduard/notify.moe/middleware/OpenGraph.go:22 +0x7b
github.com/animenotifier/notify.moe/middleware.HTTPSRedirect.func1(0xf73f20, 0xc01b669b80, 0xc15061, 0xc00a496b15)
/home/eduard/notify.moe/middleware/HTTPSRedirect.go:21 +0x1a1
github.com/animenotifier/notify.moe/middleware.Recover.func1(0xf73f20, 0xc01b669b80, 0x0, 0x0)
/home/eduard/notify.moe/middleware/Recover.go:38 +0x92
github.com/aerogo/aero.(*Application).ServeHTTP(0xc000766800, 0xf61340, 0xc033b1c2f0, 0xc01925ce00)
/home/eduard/go/pkg/mod/github.com/aerogo/aero@v1.3.26/Application.go:283 +0x12b
net/http.serverHandler.ServeHTTP(0xc033bf4000, 0xf61340, 0xc033b1c2f0, 0xc01925ce00)
/usr/lib/go/src/net/http/server.go:2802 +0xa4
net/http.initNPNRequest.ServeHTTP(0xf63ec0, 0xc027beb440, 0xc0381d1500, 0xc033bf4000, 0xf61340, 0xc033b1c2f0, 0xc01925ce00)
/usr/lib/go/src/net/http/server.go:3374 +0x8d
net/http.(*http2serverConn).runHandler(0xc010fa0600, 0xc033b1c2f0, 0xc01925ce00, 0xc022c1e5e0)
/usr/lib/go/src/net/http/h2_bundle.go:5713 +0x9f
created by net/http.(*http2serverConn).processHeaders
/usr/lib/go/src/net/http/h2_bundle.go:5447 +0x4eb

goroutine 1 [chan receive, 619 minutes]:
github.com/aerogo/aero.(*Application).wait(...)
/home/eduard/go/pkg/mod/github.com/aerogo/aero@v1.3.26/Application.go:203
github.com/aerogo/aero.(*Application).Run(0xc000766800)
/home/eduard/go/pkg/mod/github.com/aerogo/aero@v1.3.26/Application.go:165 +0xb6
main.main()
/home/eduard/notify.moe/main.go:23 +0x35

goroutine 6 [syscall, 619 minutes]:
os/signal.signal_recv(0x0)
/usr/lib/go/src/runtime/sigqueue.go:147 +0x9c
os/signal.loop()
/usr/lib/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
/usr/lib/go/src/os/signal/signal_unix.go:29 +0x41

goroutine 7 [select, 619 minutes]:
github.com/aerogo/cluster/server.(*Node).mainLoop(0xc0000bc2a0)
/home/eduard/go/pkg/mod/github.com/aerogo/cluster@v0.1.8/server/Node.go:98 +0x183
created by github.com/aerogo/cluster/server.(*Node).Start
/home/eduard/go/pkg/mod/github.com/aerogo/cluster@v0.1.8/server/Node.go:71 +0x156

goroutine 8 [IO wait, 123 minutes]:
internal/poll.runtime_pollWait(0x7f9d82655fb0, 0x72, 0x0)
/usr/lib/go/src/runtime/netpoll.go:184 +0x55
internal/poll.(*pollDesc).wait(0xc000020d18, 0x72, 0x0, 0x0, 0xdb9600)
/usr/lib/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
/usr/lib/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc000020d00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
/usr/lib/go/src/internal/poll/fd_unix.go:384 +0x1f8
net.(*netFD).accept(0xc000020d00, 0xc03aa3aef0, 0x536bff, 0xc015043700)
/usr/lib/go/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc0001893e0, 0xc015043700, 0x0, 0x0)
/usr/lib/go/src/net/tcpsock_posix.go:139 +0x32
net.(*TCPListener).Accept(0xc0001893e0, 0x0, 0x0, 0xe, 0x15a1800)
/usr/lib/go/src/net/tcpsock.go:261 +0x47
github.com/aerogo/cluster/server.(*Node).acceptCo
```

**Comment by akyoto** [comment]
Thanks for the detailed report!

Fixed it in the latest database patch.
